arrayfire/array.py

My previous "fix" introduced a problem. As algorithms.py import array.py and array.py uses `sum` from algorithms.py the `from .array import *` in algorithms.py as not importing anything.
This created errors when for example doing the following:
```python
arrayfire.max(arrayfire.randu(3),0)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-678a19c6fc42> in <module>()
----> 1 arrayfire.max(a,0)
/Library/Python/2.7/site-packages/arrayfire-3.1.0-py2.7.egg/arrayfire/algorithm.pyc in max(a, dim)
112     """
113     if dim is not None:
--> 114         return _parallel_dim(a, dim, backend.get().af_max)
115     else:
116         return _reduce_all(a, backend.get().af_max_all) …
```

Avoid problems with circular import

---

arrayfire/library.py

When the enum package is not available it's necessary to change the type of the _Enum_Type attributes inside a class derived from _Enum to match the type of the containing class (e.g. set the type of NONE inside the class ERR to ERR). Otherwise the behaviour with or without the enum package would be different.
- Fixes #65

Ensure that the types of the enums values are correct

---

examples/benchmarks/monte_carlo_pi.py

On my computer I get the following output:
```
ArrayFire v3.3.2 (CUDA, 64-bit Linux, build default)
Platform: CUDA Toolkit 7.5, Driver: 364.19
[0] GeForce GTX 960, 2040 MB, CUDA Compute 5.2
Monte carlo estimate of pi on device with 1 million samples: 3.146276
Average time taken: 0.396786 ms
Monte carlo estimate of pi on numpy with 1 million samples: 3.143600
Average time taken: 27.739305 ms
Monte carlo estimate of pi on host with 1 million samples: 3.142604
Average time taken: 311.017532 ms
```

Contribute a numpy example to benchmarks.

---

examples/benchmarks/bench_blas.py
examples/benchmarks/bench_fft.py

Compares the following functions
arrayfire  |  numpy |
---|---|
af.matmul  | np.dot     |
af.fft2         | np.fft.fft2 |
Also switch to timeit for benchmark measurements. timeit turns off the python garbage collection during measurements, so the results may be more accurate.

Add numpy benchmarks to fft and blas. 

---

arrayfire/features.py

In `features.py` all the methods of the Feature class have zero parameters, which makes them unusable since python requires `self` to be passed as first parameter.
Therefore
```python
class Features(object):
...
def num_features():
...
```
needs to be changed to
```python
class Features(object):
...
def num_features(self):
...
```
otherwise you receive an error: `TypeError: get_xpos() takes 0 positional arguments but 1 was given`

Add self as parameter to all methods of class Feature

---

README.md

Now the readme matches the online documentation [here](http://arrayfire.org/arrayfire-python/).

Corrected 'set_backend' command in readme.

---

tests/__init__.py
tests/__main__.py
tests/simple_tests.py

This PR makes the standalone `tests` folder an executable module by adding the missing `__init__.py`.
Now one can copy `tests` where the `arrayfire` module was built and run `python -m tests` to execute the testsuite. This is particularly useful for CI. The remaining fixes makes the standalone execution compatible with Python 3 (only absolute imports are allowed).

Fix standalone tests module.

---

arrayfire/__init__.py
arrayfire/algorithm.py
arrayfire/arith.py
arrayfire/array.py
arrayfire/data.py
arrayfire/device.py
arrayfire/features.py
arrayfire/graphics.py
arrayfire/image.py
arrayfire/library.py
arrayfire/random.py
arrayfire/signal.py
arrayfire/sparse.py
arrayfire/tests/simple/__init__.py
arrayfire/tests/simple/algorithm.py
arrayfire/tests/simple/arith.py
arrayfire/tests/simple/array_test.py
arrayfire/tests/simple/data.py
arrayfire/tests/simple/device.py
arrayfire/tests/simple/random.py
arrayfire/tests/simple/signal.py
arrayfire/tests/simple/sparse.py

- Pulls changes from #87 
- Pulls changes from #98 
- Fixes #90 
- Fixes #100

Features 3.4

---

arrayfire/array.py

All the internal functions initialize an empty array first
and use the internal pointer to get the output af_array.
However this was not releasing the handle originally created.
This created a memory leak easily fixed by not creating a handle
when the array is empty.

BUGFIX: Do not call af_create_handle for empty arrays

---

examples/benchmarks/bench_cg.py

Tests dense and sparse arrayfire behavior against numpy and scipy solutions. Works in float32 presision.

Add conjugate gradient benchmark

---

arrayfire/tests/simple/lapack.py

In my desktop, the default device is an Intel/OpenCL stuff. The lapack test fails on that with the following error:
```
ERROR:root:Traceback (most recent call last):
File "C:\git\arrayfire-python\arrayfire\tests\simple\_util.py", line 32, in run
test(verbose)
File "C:\git\arrayfire-python\arrayfire\tests\simple\lapack.py", line 42, in simple_lapack
a = af.matmulTN(a, a) + 10 * af.identity(5,5)
File "C:\git\arrayfire-python\arrayfire\blas.py", line 88, in matmulTN
MATPROP.TRANS.value, MATPROP.NONE.value))
File "C:\git\arrayfire-python\arrayfire\util.py", line 79, in safe_call
raise RuntimeError(to_str(err_str))
RuntimeError: In function class std::shared_ptr<float> __cdecl opencl::Array<float>::getMappedPtr(void) const
In file src\backend\opencl\Array.hpp:260
OpenCL Error (-59): Invalid …
```

Fix lapack test on OpenCL devices

---

arrayfire/signal.py

In the singal.py, for arrayfire.approx1, I found that the off_grid format should be float not double.  Therefore I changed it and it now works as expected.
Sorry if this is not proper procedure for fixing bugs, I am new to reporting bugs using github.

approx1 off_grid Error

---

.gitignore
arrayfire/array.py

Changes:
* `__repr__` made IDE friendly
* `to_string()` added to have a method for getting the full string representation
* memory leak after calling `af_array_to_string` fixed
I haven't make the full representation method as `__str__` because PyCharm invokes that automatically even it uses `__repr__` for display.

IDE compatible and not leaking __repr__

---

arrayfire/library.py

This fixes #131, where `arrayfire-python` attempted to load a non-existent `libforge.so.3`.

abstract out arrayfire and forge major versions from library setup

---

arrayfire/__init__.py
arrayfire/array.py
arrayfire/interop.py
arrayfire/library.py
arrayfire/tests/simple/_util.py
examples/benchmarks/bench_blas.py
examples/benchmarks/bench_cg.py
examples/benchmarks/bench_fft.py
examples/benchmarks/monte_carlo_pi.py

https://docs.python.org/2/howto/doanddont.html#except

Do not use bare except: clauses

---

arrayfire/algorithm.py

Fixing bug in sort_by_key parameters

---

arrayfire/signal.py
arrayfire/tests/simple/signal.py

I've implemented an `interp1d` and `interp2d` function similar to the one found in `scipy`. Rather than having the user manually transform the input points from [0, N-1] when using `approx1` and `approx2`, this function takes care of the transformation by taking the input data points in addition to the interpolation points.
However, there is one issue: I'm using `sum` to get a scalar value:
```
dx   = sum(x_input[1, 0, 0, 0] - x_input[0, 0, 0, 0])
pos0 = (x_interpolated - sum(x_input[0, 0, 0, 0]))/dx
```
Do you recommend using something else?

Add measured locations as parameters for approx1 and approx2

---

arrayfire/features.py
arrayfire/vision.py

orb and gloh calls were broken.
the features c++ destructor wasn't called and needed to be called explicitly in order to release its memory. I've added a __del__ method to features which calls af_release_features

vision.py fixes

---

arrayfire/sparse.py

Casted row and column index arrays to be of s32 type prior to passing in to
lib call. Previously failing due to failing assertions.
Fixes #189.

Fixed issue with create_sparse_from_host().

---

examples/benchmarks/bench_cg.py

The bench_cg test was failing to execute on the CUDA backend because two non-linear JIT nodes were being combined and caused the resulting kernel parameter size to go above the threshold. The nodes did not cross the evaluation threshold before hand. This will need to be address upstream.
Upstream issue: https://github.com/arrayfire/arrayfire/issues/2389

Workaround failure in bench_cg. Evaluate x array early

---

arrayfire/library.py

This fixes the specific path problem gh-217. I can import arrayfire and tests run. I am not having positive results with benchmarks (e.g. bench_cg.py). Something breaks down in ```calc_arrayfire()``` doing matrix solutions on the same arrays over a few iterations. Memory leak? Anyway that's another issue.

BF: check AF library paths for pkg vs source install

---

arrayfire/blas.py
arrayfire/library.py
arrayfire/signal.py

This PR adds approx functions from upstream 3.7. Writing to existing array is supported by the trailing `output=` kargs.
This PR also adds support for af_gemm. Adding a af_c{float,double}_t ctypes class was necessary as complex types aren't natively supported by ctypes (afaik). 
TODO: Not sure how to best implement fp16 type

Approx{1,2}_{v2,uniform}, af_gemm

---

arrayfire/array.py

Bitwise addition removed erroneuos logical not. This PR make af_not() available again. Additionally, adds logical and(&&) and or(||). This will differ from bitwise &, | for floating point types.

adds missing logical operations on Array

---

examples/common/idxio.py
examples/machine_learning/logistic_regression.py
examples/machine_learning/mnist_common.py

Modified version of the D3M logit demo so that it uses the existing MNIST data file in assets and it's not dependent on numpy or matplotlib. Ported from the [C++ arrayfire logit example](https://github.com/arrayfire/arrayfire/blob/master/examples/machine_learning/logistic_regression.cpp).

Added logistic regression example

---

CMakeLists.txt
README.md
arrayfire/library.py
pyproject.toml
setup.cfg
setup.py

uses skbuild to optionally build the arrayfire library during python setup.py build/install
AF_BUILD_LOCAL_LIBS=1 environment variable used to perform the build. if it is not specified, setup.py will just install the .py files skipping the binary build step. The library has also been tweaked to prefer to load from the new local arrayfire/lib directory. If it doesn't exist the default system paths will be searched as in previous releases

change setup.py to optionally build binaries in source distribution
